//tutorial-14 Layouts//
//titorial-16 Multiple Root layouts//
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"#fa3456",padding:"2rem"}}>
          <p>headers</p>
        </header>
        {children}
        <footer style={{backgroundColor:"blue",padding:"1rem"}}>footer</footer>
      </body>
    </html>
  )
}
