import { Metadata } from "next"

export const metadata:Metadata = {
  // title: 'Next.js',

  //Tutorial-18//
  title:{
    default:"Next.js Tutorial",
    template:"",
    absolute:""
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
